version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
  
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
